[package]
name = "cvt"
version = "0.2.0"
edition = "2021"


[features]
vacuity = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stubs = { path = "../stubs" }