[package]
name = "vectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cvt = { path = "../cvt" }
nondet = { path = "../nondet" }

[features]
certora-debug = []

[lib]
crate-type = ["lib"]
path = "mod.rs"
name = "vectors"
