[package]
name = "derive_nondet"
version = "0.3.0" 
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2", features = ['derive', 'parsing', 'extra-traits'] }

[lib]
proc-macro = true
