[package]
name = "cvlr-asserts"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[features]
vacuity = []
rt = []

[dependencies]
